apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 281145282112.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googleclothes:06f690d9300970f1f031fdcca819f2cdcc04e402
        ports:
        - containerPort: 80
