apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 975050282657.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googleclothes:5a2de249a639be53f348ab8e73f2b8282b7063c6
        ports:
        - containerPort: 80
