apiVersion: apps/v1
kind: Deployment
metadata:
  name: electronics-deployment
  labels:
    app: electronics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: electronics
  template:
    metadata:
      labels:
        app: electronics
    spec:
      containers:
      - name: electronics
        image: 975050282657.dkr.ecr.us-west-2.amazonaws.com/shopping-site-electronics:5a2de249a639be53f348ab8e73f2b8282b7063c6
        ports:
        - containerPort: 80
