apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 975050282657.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googlemusic:67ac4a7b9433e63218935a5779997c448fd0467a
        ports:
        - containerPort: 80
