apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 975050282657.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googlemusic:10072b58de08abca95dd59616e7a5c26e645a57d
        ports:
        - containerPort: 80
