apiVersion: apps/v1
kind: Deployment
metadata:
  name: computers-deployment
  labels:
    app: computers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: computers
  template:
    metadata:
      labels:
        app: computers
    spec:
      containers:
      - name: computers
        image: 975050282657.dkr.ecr.us-west-2.amazonaws.com/shopping-site-computers:5a2de249a639be53f348ab8e73f2b8282b7063c6
        ports:
        - containerPort: 80
