apiVersion: apps/v1
kind: Deployment
metadata:
  name: computers-deployment
  labels:
    app: computers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: computers
  template:
    metadata:
      labels:
        app: computers
    spec:
      containers:
      - name: computers
        image: 225962644762.dkr.ecr.us-west-2.amazonaws.com/shopping-site-computers:0376fbd3874dcb48d5e992137fbc87533fce9432
        ports:
        - containerPort: 80
